SET NAMES utf8mb4;

DROP TABLE IF EXISTS project_field_values; DROP TABLE IF EXISTS project_fields; DROP TABLE IF EXISTS projects;

CREATE TABLE projects (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 megnevezes VARCHAR(255) NOT NULL,
 szam VARCHAR(64),
 cim_irsz VARCHAR(16), cim_telepules VARCHAR(128), cim_utca VARCHAR(255), cim_hazszam VARCHAR(64), cim_egyeb VARCHAR(255),
 gps_lat DECIMAL(10,7) NULL, gps_lng DECIMAL(10,7) NULL,
 kezdo_datum DATE NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hUNGARIAN_CI;

CREATE TABLE project_fields (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(64) NOT NULL UNIQUE,
 label VARCHAR(255) NOT NULL,
 type ENUM('text','number','date','email','tel','textarea','select','checkbox') NOT NULL DEFAULT 'text',
 options_json JSON NULL,
 required TINYINT(1) NOT NULL DEFAULT 0,
 sort_order INT NOT NULL DEFAULT 0,
 active TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hUNGARIAN_CI;

CREATE TABLE project_field_values (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 project_id BIGINT UNSIGNED NOT NULL,
 field_id BIGINT UNSIGNED NOT NULL,
 value_text TEXT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uniq_project_field (project_id, field_id),
 CONSTRAINT fk_proj_val_proj FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
 CONSTRAINT fk_proj_val_field FOREIGN KEY (field_id) REFERENCES project_fields(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hUNGARIAN_CI;
